version: '3.8'

services:

  app:
    image: outbox-demo
    container_name: outbox-demo-app
    restart: on-failure
    build:
      context: .
    env_file:
      - .local.env
    ports:
      - "3000:3000"
    command: ["./app"]

  relay:
    image: outbox-demo
    container_name: outbox-demo-relay
    restart: on-failure
    build:
      context: .
    env_file:
      - .local.env
    command: [ "./relay" ]

  worker:
    image: outbox-demo
    container_name: outbox-demo-worker
    restart: on-failure
    build:
      context: .
    env_file:
      - .local.env
    command: [ "./worker" ]


  worker2:
    image: outbox-demo
    container_name: outbox-demo-worker2
    restart: on-failure
    build:
      context: .
    env_file:
      - .local.env
    command: [ "./worker2" ]

  test:
    image: golang:1.23
    container_name: outbox-demo-test
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .local.env
    depends_on:
      - app
      - relay
      - worker
    command: [ "go", "test", "-v", "./..." ]

networks:
  outbox: